kubeshop/testkube-operator

- client/client.go
> adding auth to kube client

- apis/script/v1/script_types.go
- config/crd/bases/tests.kubtest.io_scripts.yaml
> added input content metadata

- client/scripts/scripts.go
> feat: Add Delete and DeleteAll functions.

- client/scripts/scripts.go
- client/tests/tests.go
Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>
For unknown reason empty slice has length of 1 and 
-
-
-
> fix: added override for empty slices

- client/scripts/scripts.go
- client/tests/tests.go
- utils/utils.go
> feat: add list tags methods for scripts and tests

- apis/script/v1/script_types.go
Add git username and token for repository model
-
- New fields for Repository model - git username and token
-
> feat: add git username and token to script parameters

- .github/workflows/docker-build.yaml
- docker-bake.hcl
Add docker image build workflow
-
-
-
> feat: add docker image build

- apis/executor/v1/executor_types.go
- config/crd/bases/executor.testkube.io_executors.yaml
Add job template field for executor
-
-
-
> feat: add job template field

- apis/tests/v2/test_types.go
- apis/testsuite/v1/testsuite_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsuites.yaml
Add schedule for test and testsuite
-
-
-
> feat: add schedule for test and testsuite

- client/executors/executors.go
- client/executors/v1/executors.go
- client/executors/v1/webhooks.go
- client/scripts/scripts.go
- client/scripts/v2/scripts.go
- client/tests/tests.go
- client/tests/v2/tests.go
- client/testsuites/v1/testsuites.go
> feat: namespaced clients

- config/crd/bases/tests.testkube.io_testsuites.yaml
> fix: added params to testsuite crd

- .github/workflows/go.yml
- Dockerfile
- go.mod
- go.sum
> fix: upgrade to go 1.18

- .github/workflows/docker-build-stage.yaml
Added GH workflow to build a Docker image with commit hash tag and to trigger helm-charts deployment to Stage cluster in helm-charts repo.
-
-
-
> Trigger deploy to stage

- .github/CODEOWNERS
- apis/executor/v1/executor_types.go
- client/tests/v2/tests.go
- client/tests/v2/tests_test.go
- config/crd/bases/executor.testkube.io_executors.yaml
> feat: added validation to content and to features

- client/testsuites/v1/testsuites.go
- client/testsuites/v1/testsuites_test.go
> fix: secret validation for testsuites

- .github/workflows/docker-build.yaml
- Dockerfile
- docker-bake.hcl
Added arm platform for building Docker image. Added Go cross compilation.
> Add arm image

- client/tests/v2/tests.go
> fix: return secrets for list

- client/tests/v2/tests.go
- client/testsuites/v1/testsuites.go
store secret vars history
-
-
-
> feat: store secret vars history

- apis/tests/v2/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
commit parameter for repository
-
-
-
> feat: commit parameter for repository

- apis/tests/v2/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> fix: remove depth

- client/tests/v2/tests.go
list tests by names method
-
-
-
> feat: list tests by names method

- client/executors/v1/webhooks.go
> fix: address index out of range issue

- client/executors/v1/webhooks.go
- client/executors/v1/webhooks_test.go
This PR adds tests to the webhook functionality
-
- added tests
- updated create function
-
> test: add webhook tests

- controllers/tests/test_controller.go
- controllers/testsuite/testsuite_controller.go
don't duplicate crd execution request
-
-
-
> fix: don't duplicate crd execution request

- Dockerfile
> fix: correct arch from

- apis/executor/v1/webhook_types.go
- config/crd/bases/executor.testkube.io_webhooks.yaml
> feat: add selector field to webhook

- client/tests/v2/tests.go
- client/tests/v3/test.go
- client/testsuites/v1/testsuites.go
- client/testsuites/v2/testsuites.go
> feat: add variable secret reference support

- client/tests/v3/test.go
- client/testsuites/v2/testsuites.go
> fix: add missed secret

- config/crd/patches/cainjection_in_executors.yaml
- config/crd/patches/cainjection_in_scripts.yaml
- config/crd/patches/cainjection_in_tests.yaml
- config/crd/patches/cainjection_in_testsources.yaml
- config/crd/patches/cainjection_in_testsuites.yaml
- config/crd/patches/cainjection_in_testtriggers.yaml
- config/crd/patches/cainjection_in_webhooks.yaml
- config/default/kustomization.yaml
- config/default/webhookcainjection_patch.yaml
- config/manager/kustomization.yaml
cleanup kustomize code; remove cert manager leftovers; remove typos
-
-
- `make deploy` was breaking due to cert manager leftovers
> fix: cleanup kustomize

- .github/workflows/docker-build-stage.yaml
- .github/workflows/docker-build.yaml
Job is not needed anymore
-
-
-
> fix: remove old cert creation docker build job

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> fix: remove required fields for test repository

- apis/tests/v3/test_types.go
- apis/testsource/v1/testsource_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsources.yaml
> fix: add working dir field to repository

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> feat: add job template for execution request

- client/tests/v3/test.go
- client/testsources/v1/testsources.go
> feat: don't update test and test source secrets

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> feat: add preRunScript field

- pkg/validation/tests/v1/testtrigger/types.go
- pkg/validation/tests/v1/testtrigger/util.go
> feat: add configmaps for trigger

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> feat: scraper template parameter

- apis/tests/v3/test_types.go
> fix: cert json typo

- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsources.yaml
> fix: crd definition

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
Related to https://github.com/kubeshop/testkube/issues/2482
-
-
-
> feat: add negativeTest flag to tests

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> fix: go mod not working, need a new sha for a new version

- apis/testtriggers/v1/testtrigger_types.go
- config/crd/bases/tests.testkube.io_testtriggers.yaml
> feat: test trigger condition reason model

- README.md
> fix: readme format

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> feat: mark envs deprecated

- client/executors/executors.go
- client/executors/v1/executors.go
> fix: namespace for executor list

- apis/executor/v1/executor_types.go
- config/crd/bases/executor.testkube.io_executors.yaml
- config/samples/tests_v1_testsource.yaml
> feat: add git type

- pkg/validation/tests/v1/testtrigger/types.go
> fix: rename causes

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
Variables file could not be used archived due to special characters, therefore we are uploading them
-
-
-
> fix: upload variables file

- .github/workflows/go.yml
Add tests for develop branch.
-
-
-
> add tests for develop branch

- .github/workflows/docker-build-tag.yaml
> ci: add check fir release branch

- .github/workflows/docker-build-tag.yaml
Add check for release branch
-
-
-
> ci: add check for release branch

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> fix: big variables file

- .github/workflows/docker-build-release.yaml
- .github/workflows/docker-build-tag.yaml
Rename release branch to have release/** pattern.
-
-
-
> ci: rename release branch

- apis/testtriggers/v1/testtrigger_types.go
- config/crd/bases/tests.testkube.io_testtriggers.yaml
> fix: ttl for trigger condition

- .github/workflows/docker-build-tag.yaml
This PR updates GH token var so it would be possible to push and create a PR with [chart-releaser](https://github.com/kubeshop/helm-charts/blob/develop/scripts/chart_releaser.sh#L112-L113) script.
-
-
-
> ci: rename gh token var

- client/tests/v3/test.go
- client/testsources/v1/testsources.go
> fix: remove empty username and token

- .github/workflows/docker-build-develop.yaml
- .github/workflows/docker-build-tag.yaml
Add GH acton to upload README file to the Docker registry: https://hub.docker.com/repository/docker/kubeshop/testkube-operator/general
-
-
-
> ci: add docker registry description

- .github/workflows/docker-build-release.yaml
Added workflow dispatch for release to be able to trigger it manually the first time branch is created. 
https://github.com/orgs/community/discussions/54860
-
-
-
> ci: add workflow dispatch

- client/tests/v3/test.go
- client/testsuites/v2/mock_testsuites.go
- client/testsuites/v2/testsuites.go
> fix: support external secrets for tests

- client/tests/v3/test.go
- client/testsuites/v2/mock_testsuites.go
- client/testsuites/v2/testsuites.go
> fix: support external secrets

- client/tests/v3/test.go
- client/testsuites/v2/testsuites.go
> fix: secret check

- client/tests/v3/test.go
- client/testsuites/v2/testsuites.go
* fix: secret check
* fix: remove wrong condition
-
-
-
> fix: secret check (#153)

- pkg/validation/tests/v1/testtrigger/types.go
- pkg/validation/tests/v1/testtrigger/util.go
> feat: provide known condition types

- client/tests/v3/test.go
First stage for this https://github.com/kubeshop/testkube/issues/1998
-
-
-
> fix: remove related resources on test deletion

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsources.yaml
> feat: postrun script

- .github/workflows/docker-build-release.yaml
- .github/workflows/docker-build-tag.yaml
This PR removes creation of release branch in helm-charts repo to simplify release flow.
-
-
-
> ci: remove release branch creation in helm-charts repo

- client/tests/v3/test.go
> fix: don't remove non Testkube secrets

- apis/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> feat: remove outdated description

- main.go
- pkg/cronjob/client.go
> fix: image registry (#166)

- .github/workflows/go.yml
- go.mod
- go.sum
> fix: use go 1.21

- controllers/testexecution/testexecution_controller.go
> fix: context typo

- apis/executor/v1/webhook_types.go
- config/crd/bases/executor.testkube.io_webhooks.yaml
> feat: adjust uri descrription

- pkg/client/tests/v3/test_test.go
> fix: invalid reference

- api/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
> fix: make test fields optional

- pkg/client/tests/v3/test.go
- pkg/client/testsuites/v3/testsuites.go
- pkg/secret/client.go
> fix: visibility for secrets

- api/executor/v1/executor_types.go
- config/crd/bases/executor.testkube.io_executors.yaml
> feat: data dir as working dir

- Makefile
`go get` doesn't load the binaries where expected, `go install` should be used instead.
```
✗ make generate
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
go: added github.com/fatih/color v1.7.0
go: added github.com/gobuffalo/flect v0.2.0
go: added github.com/gogo/protobuf v1.3.1
go: added github.com/google/gofuzz v1.1.0
go: added github.com/inconshreveable/mousetrap v1.0.0
go: added github.com/json-iterator/go v1.1.8
go: added github.com/mattn/go-colorable v0.1.2
go: added github.com/mattn/go-isatty v0.0.8
go: added github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: added github.com/modern-go/reflect2 v1.0.1
go: added github.com/spf13/cobra v1.0.0
go: added github.com/spf13/pflag v1.0.5
go: added golang.org/x/mod …
```
> fix: correct downloading tools with Go 1.16+

- pkg/client/tests/v3/test.go
- pkg/client/testsuites/v3/testsuites.go
- pkg/secret/client.go
The equivalent for: https://github.com/kubeshop/testkube/pull/4620
> chore: rename default secret label

- README.md
> fix: back merge

- pkg/clientset/versioned/fake/register.go
- pkg/clientset/versioned/scheme/register.go
> fix: add test source scheme

- api/testexecution/v1/testexecution_types.go
- api/tests/v3/test_types.go
- api/testsuiteexecution/v1/testsuiteexecution_types.go
- config/crd/bases/tests.testkube.io_testexecutions.yaml
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsuiteexecutions.yaml
> fix: replace args mode

- pkg/cronjob/client.go
> fix: sanitize cron job name

- LICENSE
- licenses/MIT.txt
update license conditions
-
-
-
> docs: update license conditions

- LICENSE
- licenses/MIT.txt
update license conditions
-
-
-
> docs: license folder

- pkg/client/testsuites/v3/testsuites.go
> fix: secrets update

- api/testexecution/v1/testexecution_types.go
- api/tests/v3/test_types.go
- api/testsuiteexecution/v1/testsuiteexecution_types.go
- config/crd/bases/tests.testkube.io_testexecutions.yaml
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsuiteexecutions.yaml
- pkg/client/testsuites/v3/testsuites.go
> feat: Release/v1.16.35

- pkg/client/tests/v3/mock_tests.go
- pkg/client/tests/v3/test.go
- pkg/client/testsuites/v3/mock_testsuites.go
- pkg/client/testsuites/v3/testsuites.go
> feat: [TKC-1570] disable secret var

- pkg/client/tests/v3/mock_tests.go
- pkg/client/tests/v3/test.go
- pkg/client/testsuites/v3/mock_testsuites.go
- pkg/client/testsuites/v3/testsuites.go
* feat: disable secret var
* fix: change method parameters
-
-
-
> feat: Release/v1.17.8

- api/testtriggers/v1/testtrigger_types.go
- config/crd/bases/tests.testkube.io_testtriggers.yaml
- pkg/validation/tests/v1/testtrigger/types.go
- pkg/validation/tests/v1/testtrigger/util.go
> feat: add testworkflow for triggers

- api/executor/v1/webhook_types.go
- config/crd/bases/executor.testkube.io_webhooks.yaml
> feat: testworkflow events

- api/testworkflows/v1/parameter_types.go
- api/testworkflows/v1/step_types.go
* Include container spec from `run` in expressions mechanism
> fix(testworkflows): support nested expressions in "run" and config params

- api/testworkflows/v1/types.go
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
> feat: test workflow execution namespace

- api/testexecution/v1/testexecution_types.go
- api/tests/v3/test_types.go
- api/testsuiteexecution/v1/testsuiteexecution_types.go
- config/crd/bases/tests.testkube.io_testexecutions.yaml
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/tests.testkube.io_testsuiteexecutions.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
* feat: sidecar scraper option
* fix: sidecar scraper for test workflow
-
-
-
> feat: Release v1.17.40

- api/testworkflows/v1/service_types.go
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
* allow to pass service description, same as for parallel steps
> fix(testworkflows): allow to pass service description

- internal/controller/testworkflows/testworkflow_controller.go
> fix: data typo

- internal/controller/testworkflows/testworkflow_controller.go
> fix: data typo (#272)

- api/testworkflows/v1/content_types.go
- api/testworkflows/v1/zz_generated.deepcopy.go
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
- config/rbac/role.yaml
* allow to pass `sshKey`/`sshKeyFrom` for cloning Git repositories
> feat(testworkflows): allow to pass SSH private key for cloning Git repository

- api/executor/v1/webhook_types.go
- config/crd/bases/executor.testkube.io_webhooks.yaml
Add "onStateChange" flag to webhooks to enable notification on state change only
-
-
-
> feat: [TKC-1946] "onStateChange" on webhooks

- api/executor/v1/webhook_types.go
- config/crd/bases/executor.testkube.io_webhooks.yaml
> fix: deprecate on state change

- cmd/main.go
- internal/controller/tests/test_controller.go
- internal/controller/testsuite/testsuite_controller.go
- internal/controller/testworkflows/testworkflow_controller.go
> fix: [TKC-2168] delete executions

- cmd/main.go
- internal/controller/tests/test_controller.go
- internal/controller/testsuite/testsuite_controller.go
- internal/controller/testworkflows/testworkflow_controller.go
> fix: add purge executions option

- api/testworkflows/v1/base_types.go
- api/testworkflows/v1/step_types.go
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
* feat: add options to control Test Workflow' containers isolation
* fix: make TestWorkflowSystem variables optional
> Release v2.1.0

- .github/workflows/docker-build-tag.yaml
> ci: add dispatch to release job

- api/testtriggers/v1/testtrigger_types.go
- config/crd/bases/tests.testkube.io_testtriggers.yaml
- pkg/validation/tests/v1/testtrigger/types.go
> feat: [TKC-3102] generation and resource causes

- internal/controller/testworkflows/testworkflow_controller.go
- pkg/cronjob/client.go
> fix: [TKC-3186] uid for cronjob name

- README.md
- api/tests/v3/test_types.go
- config/crd/bases/tests.testkube.io_tests.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
This PR contributes to TKC-3197
> feat: add github app auth type

- api/testworkflows/v1/service_types.go
- api/testworkflows/v1/step_types.go
- config/crd/bases/testworkflows.testkube.io_testworkflows.yaml
- config/crd/bases/testworkflows.testkube.io_testworkflowtemplates.yaml
> fix: [TK-3315] support timeout expressions

- internal/controller/testworkflows/testworkflow_controller.go
> fix: use api test workflow request

- config/crd/crd.go
> feat: [TKC-3569] add crd package
